global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "nodes"
    static_configs:
      - targets: ["node01:9100"]
        labels:
          node: "node01"
      - targets: ["node02:9100"]
        labels:
          node: "node02"
