apiVersion: v1
data:
  apikey: emFDRUxnTC0waW1mbmM4bVZMV3dzQWF3allyNFJ4LUFmNTBERHF0bHg=
  password: cGFTc3cwckQtMWVyVC1kaVM=
  username: YWRtaW4tZGV2LWdyb3Vw
kind: Secret
metadata:
  creationTimestamp: null
  name: app-crds
