apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: credentials/data/app
  name: app-crds
stringData:
  apikey: dgg7B3BaaeBleqE
  password: skdjD432JDjd
  username: bob
type: Opaque
---
