pipeline {
    agent any

    tools {
        // Instala la versión de Maven configurada como "maven-398" y la añade al PATH.
        maven "maven-398"
    }

    stages {
        stage('Check Maven') {
            steps {
                sh "if ! command -v mvn; then echo 'Maven not found!'; exit 1; fi"
            }
        }

        stage('Build') {
            steps {
                git branch: 'main', url: 'http://localhost:5555/dasher-org/jenkins-hello-world.git'
                sh "mvn clean package -DskipTests=true"
            }
        }

        stage('Unit Test') {
            steps {
                sh "mvn test"
            }
        }

        stage('Local Deployment') {
            steps {
                // JENKINS_NODE_COOKIE evita que Jenkins mate el proceso de Java al terminar la etapa
                sh """
                    export JENKINS_NODE_COOKIE=dontKillMe
                    java -jar target/hello-demo-*.jar > /dev/null 2>&1 &
                """
            }
        }

        stage('Integration Testing') {
            steps {
                sh "sleep ${params.SLEEP_TIMER}"
                sh """ curl -s http://localhost:${params.APPLICATION_PORT}/hello | grep -i "Hello, KodeKloud community!" """
            }
        }
    }
}

