<?xml version='1.1' encoding='UTF-8'?>
<build>
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UpstreamCause>
            <upstreamProject>ascii-test-job</upstreamProject>
            <upstreamUrl>job/ascii-test-job/</upstreamUrl>
            <upstreamBuild>1</upstreamBuild>
            <upstreamCauses>
              <hudson.model.Cause_-UserIdCause>
                <userId>admin</userId>
              </hudson.model.Cause_-UserIdCause>
            </upstreamCauses>
          </hudson.model.Cause_-UpstreamCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
  </actions>
  <queueId>3</queueId>
  <timestamp>1779584642197</timestamp>
  <startTime>1779584642199</startTime>
  <result>SUCCESS</result>
  <duration>2830</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>/var/lib/jenkins/workspace/ascii-build-job</workspace>
  <hudsonVersion>2.479.1</hudsonVersion>
  <scm class="hudson.scm.NullChangeLogParser"/>
  <culprits class="java.util.Collections$UnmodifiableSet">
    <c class="sorted-set"/>
  </culprits>
</build>